### ISSUE TITLE
🐛 Bug: yarn build error

### ISSUE THREAD

**Issue by spacether** [json-schema-org/website#702]
### Describe the bug

When running yarn build on main with node v20 I get:
```
Error occurred prerendering page "/overview/code-of-conduct". Read more: https://nextjs.org/docs/messages/prerender-error
Error: ENOENT: no such file or directory, open 'pages/overview/code-of-conduct/_index.md'
    at Object.readFileSync (node:fs:448:20)
    at getStaticProps (/Users/justinblack/programming/website/.next/server/pages/overview/code-of-conduct.js:1:1395)
    at /Users/justinblack/programming/website/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:4070
    at /Users/justinblack/programming/website/node_modules/next/dist/server/lib/trace/tracer.js:131:36
    at NoopContextManager.with (/Users/justinblack/programming/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/justinblack/programming/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/justinblack/programming/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/justinblack/programming/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/justinblack/programming/website/node_modules/next/dist/server/lib/trace/tracer.js:120:103

```

### Steps To Reproduce

run yarn build on main with node 20

### Expected Behavior

no errors thrown, site built

### Device Information [optional]

```markdown
- OS: macOs Monterey v12.7.4
- Browser: n/a
- version: n/a
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by aialok** [comment]
Hey @spacether, Thanks for the issue.

Did you run this both commands?


![Screenshot_20240521_021511_GitHub.jpg](https://github.com/json-schema-org/website/assets/66772290/d1640400-bab5-43cb-9ec7-81d2c8a801c0)

The project uses git submodules too so we need to install that things too.

Hope this will work.

Thank you : )

**Comment by spacether** [comment]
Ah, I missed that. That solved my issue; closing it now. Thanks!
